services:
  # --- SERVICIO 1: BASE DE DATOS POSTGRESQL ---
  db:
    image: postgres:16-alpine
    container_name: customer_churn_db
    restart: always
    environment:
      POSTGRES_USER: ds_user
      POSTGRES_PASSWORD: chiara01!
      POSTGRES_DB: customer_churn
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- SERVICIO 2: ENTORNO DE TRABAJO DATA SCIENCE ---
  app:
    build: .
    container_name: customer_churn_app
    restart: always
    volumes:
      - .:/workspace
    environment:
      - DATABASE_URL=postgresql://ds_user:chiara01!@db:5432/customer_churn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    depends_on:
      - db

  # --- SERVICIO 3: INTERFAZ DE STREAMLIT ---
  streamlit:
    build: .
    container_name: customer_churn_streamlit
    restart: always
    volumes:
      - .:/workspace
    ports:
      - "8501:8501"
    command: streamlit run 04.streamlit/app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - db

volumes:
  pgdata:
